# Generated by Django 5.1.6 on 2025-03-16 19:41

import settings.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=settings.fields.CompressedImageField(blank=True, null=True, upload_to='church_logos/'),
        ),
    ]
