# Generated by Django 5.1.6 on 2025-02-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_ministry_age_group_remove_ministry_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
