# Generated by Django 5.1.6 on 2025-03-16 20:24

import settings.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_ministry_ppoi_alter_ministry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=settings.fields.CompressedImageField(blank=True, help_text="Member's profile picture.", null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='image',
            field=settings.fields.CompressedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
