# Generated by Django 5.1.3 on 2025-02-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member'),
        ),
        migrations.AddField(
            model_name='staff',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
