# Generated by Django 5.1.6 on 2025-02-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member'),
        ),
    ]
