# Generated by Django 5.1.3 on 2025-02-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('contact', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.poll'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='membership.member'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='community.survey'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='membership.member'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to='contact.staff'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_opportunities', to='membership.ministry'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.volunteeropportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerapplication',
            unique_together={('member', 'opportunity')},
        ),
    ]
