# Generated by Django 5.1.6 on 2025-04-07 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_carouselitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True, help_text='A short summary of the devotional.', null=True)),
                ('content', models.TextField()),
                ('scripture_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional URL for the devotional image.', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Schedule this devotional for a specific day.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark this devotional as featured.')),
                ('published', models.BooleanField(default=True, help_text='Control whether this devotional is publicly visible.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when the devotional was published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
