# Generated by Django 5.1.6 on 2026-01-03 07:35

from django.db import migrations


def update_site_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    # Update or create the site with ID 1
    Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': 'www.kumasicentralchurchofchrist.com',
            'name': 'Kumasi Central Church of Christ'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_devotional'),
        ('sites', '0001_initial'), # Ensure sites app is initialized
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
