# Generated by Django 5.1.6 on 2025-02-13 10:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Content of the blog post'),
        ),
    ]
