# Generated by Django 5.1.3 on 2025-02-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_initial'),
        ('event', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, through='event.EventRegistration', to='membership.member'),
        ),
        migrations.AddField(
            model_name='outreachprogram',
            name='organizers',
            field=models.ManyToManyField(related_name='outreach_programs', to='contact.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'member')},
        ),
    ]
