# Generated by Django 5.1.6 on 2025-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_ppoi_galleryimage_ppoi_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, default='all', max_length=50),
        ),
    ]
