# Generated by Django 5.1.6 on 2025-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_galleryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
