# Generated by Django 5.1.6 on 2025-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchcalendar',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Church Calendar Event', 'verbose_name_plural': 'Church Calendar Events'},
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
