# Generated by Django 5.1.6 on 2025-03-16 20:24

import settings.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_churchcalendar_options_churchcalendar_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=settings.fields.CompressedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=settings.fields.CompressedImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
