# Generated by Django 5.1.6 on 2025-03-27 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_ppoi_remove_galleryimage_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchcalendar',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Church Calendar Event', 'verbose_name_plural': 'Church Calendar Events'},
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='time',
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Check if the event lasts all day'),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='category',
            field=models.CharField(choices=[('service', 'Service'), ('meeting', 'Meeting'), ('youth', 'Youth Event'), ('outreach', 'Outreach'), ('special', 'Special Event')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='End date and time of the event (optional)', null=True),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as a featured event for special display'),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the event', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time of the event'),
        ),
    ]
