# Generated by Django 5.1.6 on 2025-03-27 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_churchcalendar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchcalendar',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Church Calendar Event', 'verbose_name_plural': 'Church Calendar Events'},
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='category',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='location',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='churchcalendar',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
