# Generated by Django 5.1.6 on 2025-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_churchcalendar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchcalendar',
            name='category',
            field=models.CharField(choices=[('service', 'Service'), ('meeting', 'Meeting'), ('youth', 'Youth Event'), ('outreach', 'Outreach'), ('special', 'Special Event'), ('other', 'other')], default='service', max_length=20),
        ),
    ]
