# Generated by Django 5.1.3 on 2025-02-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='member',
            field=models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='allowed_days',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.day'),
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_days',
            field=models.ManyToManyField(related_name='roles', to='worship.day'),
        ),
    ]
