# Generated by Django 5.1.3 on 2025-02-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0002_day_alter_appointment_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
    ]
