# Generated by Django 5.1.3 on 2025-02-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='lord_supper_helpers',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ushers',
        ),
    ]
