# Generated by Django 5.1.3 on 2025-02-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0004_remove_appointment_lord_supper_helpers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
