# Generated by Django 5.1.3 on 2025-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0005_appointment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], max_length=10, unique=True),
        ),
    ]
