# Generated by Django 5.1.6 on 2025-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0006_appointment_reminder_sent_alter_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
