# Generated by Django 5.1.6 on 2025-03-20 13:52

import django.core.files.storage
import settings.fields
import worship.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0012_remove_sermon_ppoi_alter_livestream_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=settings.fields.SupabaseFileField(help_text='Upload the resource file', storage=django.core.files.storage.FileSystemStorage(), upload_to='resources/', validators=[worship.models.validate_document_file, worship.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='document',
            field=settings.fields.SupabaseFileField(blank=True, help_text='Optional document file (PDF, notes, etc.)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='sermons/documents/', validators=[worship.models.validate_document_file, worship.models.validate_file_size]),
        ),
    ]
