# Generated by Django 5.1.6 on 2025-04-14 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0013_alter_resource_file_alter_sermon_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='series',
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date'], 'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='video_url',
        ),
        migrations.AddField(
            model_name='sermon',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL to the Facebook page where the sermon can be watched', null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this sermon as featured on the site'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for a sermon image (if available)', null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief summary or outline of the sermon'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full text transcript of the sermon (optional)'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the sermon was delivered'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a sermon thumbnail image', null=True, upload_to='sermon_images/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(default='Unknown Preacher', help_text='Name of the preacher or minister', max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='scripture_reference',
            field=models.CharField(blank=True, help_text='Scripture passage (e.g., John 3:16-18)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='SermonSeries',
        ),
    ]
