# Generated by Django 5.1.6 on 2025-04-19 10:24

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0015_alter_livestream_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='yt_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='YouTube replay URL (after FB expires)', null=True),
        ),
    ]
