# Generated by Django 5.1.6 on 2025-04-19 11:16

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0016_livestream_yt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Indicates if the sermon is currently live'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='yt_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
