# Generated by Django 5.1.6 on 2025-04-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0017_sermon_is_live_sermon_yt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='yt_url',
        ),
    ]
